variables:
- group: var-group-devops-config-as-code

stages:
- stage: Apply_Policies
  displayName: 'Apply Policies'
  jobs:
    - job: Job_Politicas_Repos
      displayName: 'Apply Policies Repos'
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: python -m pip install --upgrade pip
        displayName: 'Install tools'
      - script: pip install -r requirements.txt
        displayName: 'Install requirements'
      - script: PAT=$(personal_access_token) python app.py
        displayName: 'Apply Policies'